Centroserv/Models/Despesas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Centroserv.Models.ValoresPadroes;

namespace Centroserv.Models
{
    public class Despesas
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string Descricao { get; set; }
        public TipoDespesa TipoDespesa { get; set; }

        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public double Valor { get; set; }
        public string Data { get; set; }

        public Clientes Cliente { get; set; }

    }


}

Centroserv/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Centroserv.Services;
using Centroserv.ViewModels;
using Centroserv.Models;
using Centroserv.Models.ValoresPadroes;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace Centroserv.Controllers
{
    
    public class DespesasController : Controller
    {
        private IDespesas _despesa;
        private IClientes _clientes;

        
        public DespesasController(IDespesas despesa, IClientes clientes)
        {
            _despesa = despesa;
            _clientes = clientes;
        }


        // GET: Despesas
        [Route("/despesas/{ano?}/{mes?}")]
        public ActionResult Index(string ano, string mes)
        {
            var model = new DespesasIndexViewModel();
            model.Despesas = _despesa.GetAll(ano,mes);
            foreach(var i in model.Despesas)
            {
                i.Cliente = _clientes.Get(i.IdCliente);
            }

            int auxMes, auxAno;

            bool flagMes = int.TryParse(mes, out auxMes); 
            bool flagAno = int.TryParse(ano, out auxAno);

            if (!flagAno || !flagMes)
            {
                ViewBag.Ano = DateTime.Now.Year;
                //ViewBag.Mes = DateTime.Now.Month;
            }
            else
            {
                ViewBag.Mes = auxMes;
                ViewBag.Ano = auxAno;
            }
            model.ListaClientes = _clientes.GetAll();
            return View(model);
        }

        // GET: Despesas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }



        // POST: Despesas/Create
        [Route("/despesas/create/")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            var model = new Despesas();
            model.IdCliente = Convert.ToInt16(collection["IdCliente"]);
            model.TipoDespesa = (TipoDespesa)Enum.Parse(typeof(TipoDespesa), collection["TipoDespesa"]);
            int.TryParse(collection["Valor"], out int newValor);
            model.Valor = newValor;
            model.Descricao = collection["Descricao"];
            model.Data = collection["Data"];
            _despesa.Add(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: Despesas/Edit/5
        [Route("api/despesas/edit/{id}")]
        public ActionResult Edit(int id)
        {
            var model = _despesa.Get(id);
            string modelJson = JsonConvert.SerializeObject(
                new
                {
                    dados = model
                });
            return Ok(modelJson);
        }

        // POST: Despesas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        [Route("/despesas/delete/")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            _despesa.Delete(Convert.ToInt16(collection["idToBeDeleted"]));
            return RedirectToAction(nameof(Index));
        }
    }
}

Centroserv/Views/Despesas/Create.cshtml
@using Centroserv.Models
@model Centroserv.ViewModels.ClientesEditViewModel

@{
    ViewBag.Title = "Create";
}


<h2>Adicionar Despesa</h2>
<br />



<form method="post">
    <div class="row ">
        <div class="col-7 text-info">
            <div class="form-row">
                <div class="form-group col-md-2 ">
                    <label for="slctTipo">Estabelecimento</label>
                    <select asp-for="Tipo" class="form-control" id="slctTipo" asp-items="@Html.GetEnumSelectList<TipoEstabelecimento>()"></select>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Alias">Alias</label>
                    <input asp-for="Alias" class="form-control" placeholder="Ex. Jupiter">
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Razao">Razao Social</label>
                    <input asp-for="Razao" class="form-control">
                </div>
            </div>


            <div class="form-row text-info">
                <div class="form-group col-md-5">
                    <label asp-for="Endereco">Endereco</label>
                    <input asp-for="Endereco" class="form-control">
                </div>
                <div class="form-group col-md-3 text-info">
                    <label asp-for="Bairro">Bairro</label>
                    <input asp-for="Bairro" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Cidade">Cidade</label>
                    <input asp-for="Cidade" class="form-control">
                </div>
                <div class="form-group col-md-1 text-info">
                    <label asp-for="UF">UF</label>
                    <input asp-for="UF" class="form-control">
                </div>
            </div>
            <hr />
            <div class="form-row text-info">
                <div class="form-group col-md-3">
                    <label asp-for="Contato">Tipo Contato</label>
                    <select asp-for="Contato" asp-items="@Html.GetEnumSelectList<TipoContato>()" class="form-control">
                        <option value="-1"></option>
                    </select>
                </div>

                <div class="form-group col-md-4 text-info">
                    <label asp-for="NomeContato">Nome</label>
                    <input class="form-control" asp-for="NomeContato">
                </div>
                <div class="form-group col-md-5">
                    <label asp-for="EnderecoContato">Endereco</label>
                    <input class="form-control" asp-for="EnderecoContato">
                </div>
            </div>
            <div class="form-row text-info">

                <div class="form-group col-md-6">
                    <label asp-for="EmailContato">Email</label>
                    <input class="form-control" asp-for="EmailContato">
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="FoneContato">Fone</label>
                    <input class="form-control" asp-for="FoneContato">
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="CelularContato">Celular</label>
                    <input class="form-control" asp-for="CelularContato">
                </div>
            </div>


            <br />




            <div class="accordion" id="accordionExample">

                <div class="card">
                    <div class="card-header " id="headingThree">
                        <h2 class="mb-0">
                            <button class="btn btn-link " type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Agenda
                            </button>
                        </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body">
                            <div>
                                <h6 class="text-secondary">Carmen Miranda</h6>
                                <span class="text-secondary">Inicio: 10/Out/2018</span>
                            </div>
                            <br />
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Segunda</th>
                                        <th scope="col">Quarta</th>
                                        <th scope="col">Sexta</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>10:00-15:00</td>
                                        <td>10:00-15:00</td>
                                        <td>10:00-15:00</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header " id="headingTwo">
                        <h2 class="mb-0">
                            <button class="btn btn-link " type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Ocorrencias
                            </button>
                        </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            <div>
                                <h6 class="text-secondary">Carmen Miranda</h6>
                                <span class="text-secondary">Inicio: 10/Out/2018</span>
                            </div>
                            <br />
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Segunda</th>
                                        <th scope="col">Quarta</th>
                                        <th scope="col">Sexta</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>10:00-15:00</td>
                                        <td>10:00-15:00</td>
                                        <td>10:00-15:00</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <br />
            <br />
            <input class="btn btn-success" type="submit" name="save" value="Gravar" style="width:20%" />

        </div>


        <div class="col-4 bg-light">
            <h4>Contrato</h4>
            <div class="form-group">
                <label asp-for="SelectedImobiliaria">Imobiliaria / Administradora</label>
                <select asp-for="SelectedImobiliaria" class="form-control" id="slcImobiliaria" asp-items="@(new SelectList(Model.ListaImobiliarias,"Id","Nome"))">
                    <option value="-1"></option>
                </select>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label asp-for="Inicio">Inicio Contrato</label>
                    <input class="form-control text-success txtData" asp-for="Inicio">
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Fim">Fim Contrato</label>
                    <input class="form-control text-danger txtData" asp-for="Fim">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <label asp-for="ValorMaximoMaterial">Limite Material (R$)</label>
                    <input class="form-control text-secondary " asp-for="ValorMaximoMaterial">
                </div>
            </div>
            <div class="form-group form-check text-primary">
                <input asp-for="MaterialLimpeza" class="form-check-input">
                <label class="form-check-label" asp-for="MaterialLimpeza">Material de limpeza fornecido pelo cliente</label>
            </div>
            <div class="form-group">
                <label asp-for="Observacao">Observacao</label>
                <textarea class="form-control" asp-for="Observacao" rows="4"></textarea>
            </div>

            <h5>Servicoes Prestados</h5>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="SerLimpeza">
                <label class="form-check-label" asp-for="SerLimpeza">Limpeza</label>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="SerZeladoria">
                <label class="form-check-label" asp-for="SerZeladoria">Zeladoria</label>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="SerPortaria">
                <label class="form-check-label" asp-for="SerPortaria">Portaria</label>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="SerGramado">
                <label class="form-check-label" asp-for="SerGramado">Manutencao Gramado</label>
            </div>



            <div class="form-group">
                <label asp-for="Equipamentos">Equipamentos alocados a esse cliente</label>
                <textarea class="form-control" asp-for="Equipamentos" rows="3"></textarea>
            </div>
        </div>
    </div>
    <br />


</form>

<p>

</p>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Funcionarios Alocados</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Inicio</th>
                            <th scope="col">Fim</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Carmen Miranda</td>
                            <td>01/Jan/2019</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Simone Ximena</td>
                            <td>25/Set/2012</td>
                            <td>20/Out/2018</td>
                        </tr>
                        <tr>
                            <td>Daine da Silva</td>
                            <td>25/Set/2010</td>
                            <td>20/Out/2012</td>

                        </tr>
                    </tbody>
                </table>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>



<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>

Centroserv/Views/Despesas/Index.cshtml
@using Centroserv.Models.ValoresPadroes
@model Centroserv.ViewModels.DespesasIndexViewModel

@{
    ViewData["Title"] = "Index";
}



<div class="row">
    <div class="col-6 text-info text-right"><h2>Despesas</h2></div>
   
</div>
<div class="row">
     <div class="col-6 text-left">
        <p>
            <button class="btn btn-primary" data-toggle="modal" data-target="#modal_add" href="#">Nova Despesa</button>
        </p>
    </div>
</div>

<br />

<partial name="_MesAno" />
<br />

<div class="row">
    <div class="col-lg-12">
        <table class="table" id="tableDespesas">
            <thead>
                <tr>
                    <th>
                        Data
                    </th>
                    <th>
                        Tipo Despesa
                    </th>
                    <th>
                        Valor
                    </th>
                    <th>
                        Cliente
                    </th>
                    <th>
                        Descricao Despesa
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Despesas)
                {
                    <tr class="@(item.TipoDespesa == Centroserv.Models.ValoresPadroes.TipoDespesa.Rembolso ? "table-danger" : "table-defasult") ">
                        <td>
                            @Html.DisplayFor(modelItem => item.Data)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoDespesa)
                        </td>
                        <td class="NumValor">
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente.Alias)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td>
                            <a href="#modal_edit" data-toggle="modal" data-id="@item.Id" class="text-info">Editar</a>
                            <span class="text-light"> | </span>
                            <a href="#ModalConfirmaDelete" data-toggle="modal" data-id="@item.Id" data-despesa="@(item.Descricao + " ("+item.TipoDespesa+" "+item.Data+")")" class="text-danger"> Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>





<!-- Modal -->
<div class="modal fade" id="modal_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Adicionar Despesa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Despesas" asp-action="Create" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-5">
                                <label asp-for="Data"></label>
                                <input asp-for="Data" class="txtData form-control" value="@(DateTime.Now.Date.ToString("dd/MM/yyyy"))" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="IdCliente">Cliente</label>
                        <select asp-for="IdCliente" class="form-control" asp-items="@(new SelectList(Model.ListaClientes,"Id","Alias"))"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="TipoDespesa"></label>
                        <select asp-for="TipoDespesa" class="form-control" asp-items="@Html.GetEnumSelectList<TipoDespesa>()"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descricao"></label>
                        <input asp-for="Descricao" class="form-control" />
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-5">
                                <label asp-for="Valor"></label>
                                <input asp-for="Valor" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <input type="submit" name="save" class="btn btn-primary" value="Salvar">
                </div>
            </form>
        </div>
    </div>
</div>





<!-- Modal -->
<div class="modal fade" id="modal_edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar Despesa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Despesas" asp-action="Edit" method="post" id="form_edit">
                <div class="modal-body">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-5">
                                <label asp-for="Data" class="text-info"></label>
                                <input asp-for="Data" class="txtData form-control" value="@(DateTime.Now.Date.ToString("dd/MM/yyyy"))" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="IdCliente" class="text-info">Cliente</label>
                        <select asp-for="IdCliente" class="form-control" asp-items="@(new SelectList(Model.ListaClientes,"Id","Alias"))"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="TipoDespesa" class="text-info"></label>
                        <select asp-for="TipoDespesa" class="form-control" asp-items="@Html.GetEnumSelectList<TipoDespesa>()"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descricao" class="text-info"></label>
                        <input asp-for="Descricao" class="form-control" />
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-5">
                                <label asp-for="Valor" class="text-info"></label>
                                <input asp-for="Valor" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <input type="submit" name="save" class="btn btn-primary" value="Salvar">
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="ModalConfirmaDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirma</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-action="delete" method="post">
                <div class="modal-body">
                    <input type="hidden" id="idToBeDeleted" name="idToBeDeleted" value="" />
                    <h5 class="text-secondary">
                        Confirma a exclusao de
                        <span class="text-primary" id="sDespesa"></span>?                                                                                                <p></p>
                    </h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Nao</button>
                    <input type="submit" name="name" class="btn btn-danger" value="Sim" />
                </div>
            </form>
        </div>
    </div>
</div>




<script>
    function exclui(Id) {
        //let dado = {
        //    "id": Id
        //};
        //$.post("despesas/delete/", dado, function (result) {
        //    console.log(result);
        //});
    }

    //triggered when modal is about to be shown
    $('#ModalConfirmaDelete').on('show.bs.modal', function (e) {
        //get data-id attribute of the clicked element
        var Despesa = $(e.relatedTarget).data('despesa');
        var Id = $(e.relatedTarget).data('id');
        //populate the textbox
        //$(e.currentTarget).find('input[name="sNome"]').val(Nome);
        $("#sDespesa").html(Despesa);
        $("#idToBeDeleted").attr("value", Id);
        //$("#btnDeleteModal").attr("onclick", "exclui(" + Id + ")");

    });


    $('#modal_edit').on('show.bs.modal', function (e) {
        var idDespesa = $(e.relatedTarget).data('id');
        //var $doc = $('#main');
        

        $.ajax({
            type: 'GET',
            url: 'https://localhost:44335/api/despesas/edit/' + idDespesa,
            success: function (retorno) {
                var objDespesa = JSON.parse(retorno)
                console.log(objDespesa.dados);
                $("#modal_edit #Data").val(objDespesa.dados.Data);
                //$("#modal_edit #IdCliente").attr("value", objDespesa.dados.IdCliente);
                $("#modal_edit #IdCliente").val(objDespesa.dados.IdCliente);
                $("#modal_edit #TipoDespesa").val(objDespesa.dados.TipoDespesa);
                $("#modal_edit #Descricao").val(objDespesa.dados.Descricao);
                var valorFormatado = parseFloat(Math.round(objDespesa.dados.Valor * 100) / 100).toFixed(2);
                $("#modal_edit #Valor").val(valorFormatado);

            },
            error: function (e) {
                console.log(e);
            }

        });


    });

</script>


@*<script>
        $('#modal_add').on('shown.bs.modal', function () {
            $('#myInput').trigger('focus')
        })
    </script>*@







<script>
    $(document).ready(function () {
        $('#tableDespesas').DataTable({
            "dom": 'frtip',
            columnDefs: [{
                targets: [0, 1, 2, 3],
                className: 'mdl-data-table__cell--non-numeric'
            }],
            "language": {
                "search": "Buscar:"
            }

        });
    });
</script>