Centroserv/Models/Grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Centroserv.Models.ValoresPadroes;

namespace Centroserv.Models
{
    public class Grade
    {
        public int Id { get; set; }
        public int IdFuncionario { get; set; }
        public int IdCliente { get; set; }
        public bool Ativo { get; set; }
        public string Entrada { get; set; }
        public string Saida { get; set; }

        public string Inicio { get; set; }

        public string Fim { get; set; }

        public DiasGrade Dia { get; set; }

        public Funcionarios Funcionarios { get; set; }

        public Clientes Clientes { get; set; }

    }
}

Centroserv/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Centroserv.Models;
using Centroserv.Services;
using Centroserv.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Centroserv
{
    public class ClientesController : Controller
    {
        // GET: /<controller>/

        private IClientes _clientes;
        private IImobiliarias _imobiliarias;

        public ClientesController(IClientes clienteData, IImobiliarias imobiliariasData)
        {
            _clientes = clienteData;
            _imobiliarias = imobiliariasData;
        }

        public IActionResult Index()
        {
            var model = new ClientesIndexViewModel();
            model.Clientes = _clientes.GetAll();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new ClientesEditViewModel();
            model.ListaImobiliarias = _imobiliarias.GetAll().ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id != 0)
            {
                var clie = _clientes.Get(id);
                if (clie == null)
                {
                    NotFound();
                }
                var model = new ClientesEditViewModel();
                model.Alias = clie.Alias;
                model.Bairro = clie.Bairro;
                model.Cidade = clie.Cidade;
                model.Endereco = clie.Endereco;
                model.Razao = clie.Razao;
                model.Tipo = clie.Tipo;
                model.UF = clie.UF;
                model.SelectedImobiliaria = clie.SelectedImobiliaria;
                model.ListaImobiliarias = _imobiliarias.GetAll().ToList();

                model.Contato = clie.Contato;
                model.Equipamentos = clie.Equipamentos;
                model.Fim = clie.Fim;
                model.NomeContato = clie.NomeContato;
                model.EnderecoContato = clie.EnderecoContato;
                model.FoneContato = clie.FoneContato;
                model.CelularContato = clie.CelularContato;
                model.EmailContato = clie.EmailContato;
                model.Inicio = clie.Inicio;
                model.MaterialLimpeza = clie.MaterialLimpeza;
                model.Observacao = clie.Observacao;
                model.SerGramado = clie.SerGramado;
                model.SerLimpeza = clie.SerLimpeza;
                model.SerPortaria = clie.SerPortaria;
                model.SerZeladoria = clie.SerZeladoria;
                model.ValorMaximoMaterial = clie.ValorMaximoMaterial;
                model.Latitude = clie.Latitude;
                model.Longitude = clie.Longitude;
                return View(model);
            }

            return RedirectToAction(nameof(Index));
        }





        [HttpPost]
        public IActionResult Edit(Clientes cli)
        {
            if (ModelState.IsValid)
            {
                _clientes.Update(cli);
                return RedirectToAction("Index"); // Redirect is a common practice to avoid the user to refresh the browser and resubmit the form
            }
            else
            {
                return View();
            }
        }








        public IActionResult Delete(int id)
        {
            _clientes.Delete(id);
            return RedirectToAction(nameof(Index));
        }










        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Clientes model)
        {
            if (ModelState.IsValid) {
                var newCliente = new Clientes();
                newCliente.Alias = model.Alias;
                newCliente.Bairro = model.Bairro;
                newCliente.Cidade = model.Cidade;
                newCliente.Endereco = model.Endereco;
                newCliente.Razao = model.Razao;
                newCliente.Tipo = model.Tipo;
                newCliente.UF = model.UF;
                newCliente.SelectedImobiliaria = model.SelectedImobiliaria;
                newCliente.Contato = model.Contato;
                newCliente.EmailContato = model.EmailContato;
                newCliente.CelularContato = model.CelularContato;
                newCliente.Contato = model.Contato;
                newCliente.EnderecoContato = model.EnderecoContato;
                newCliente.Equipamentos = model.Equipamentos;
                newCliente.Fim = model.Fim;
                newCliente.FoneContato = model.FoneContato;
                newCliente.Inicio = model.Inicio;
                newCliente.MaterialLimpeza = model.MaterialLimpeza;
                newCliente.NomeContato = model.NomeContato;
                newCliente.Observacao = model.Observacao;
                newCliente.SerGramado = model.SerGramado;
                newCliente.SerLimpeza = model.SerLimpeza;
                newCliente.SerPortaria = model.SerPortaria;
                newCliente.SerZeladoria = model.SerZeladoria;
                newCliente.ValorMaximoMaterial = model.ValorMaximoMaterial;



                newCliente = _clientes.Add(newCliente);

                //return RedirectToAction(nameof(Edit), new { id = newCliente.Id });
                return RedirectToAction(nameof(Index));

            }
            else
            {
                return View();
            }

        }
    }
}

Centroserv/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Centroserv.Services;
using Centroserv.ViewModels;
using Centroserv.Models;

namespace Centroserv.Controllers
{
    public class GradeController : Controller
    {
        private IGrade _grade;
        private IFuncionarios _funcionarios;
        private IClientes _clientes;

        public GradeController(IGrade grade, IFuncionarios funcionarios, IClientes clientes)
        {
            _grade = grade;
            _funcionarios = funcionarios;
            _clientes = clientes;
        }

        
        //[Route("")]
        [Route("grade/index/{MostraTodos?}")]
        public IActionResult Index(string MostraTodos) //id aqui eh usado como flag (mostra todos os horarios ou so ativos)
        {
            var model = new GradeIndexViewModel();
            if (string.IsNullOrEmpty(MostraTodos))
            {
                model.GradeDeHorario = _grade.GettAll(null, null, true);
            }
            else
            {
                model.GradeDeHorario = _grade.GettAll(null, null, false);
            }
            //var ClienteDistinct = model.GradeDeHorario.Select(e => new { e.IdFuncionario, e.IdCliente }).Distinct();
            var ClienteDistinct = from x in model.GradeDeHorario
                                  group x by new { x.IdCliente, x.IdFuncionario } into newGroup
                                  orderby newGroup.Key.IdFuncionario
                                  select newGroup;
                                  
         
            model.GradeClientesUnico = ClienteDistinct;
            model.FuncionariosTodos = _funcionarios.GetAll();
            model.ClientesTodos = _clientes.GetAll();
            return View(model);
        }


        [HttpGet]
        public IActionResult Del(int id)
        {
            var model = _grade.Delete(id);
            return RedirectToAction(nameof(Index));
        }




        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = new GradeIndexViewModel();
            model.GradeDeHorario = _grade.GettAll(null, null, null);
            //var ClienteDistinct = model.GradeDeHorario.Select(e => new { e.IdFuncionario, e.IdCliente }).Distinct();
            var ClienteDistinct = from x in model.GradeDeHorario
                                  group x by new { x.IdCliente, x.IdFuncionario } into newGroup
                                  orderby newGroup.Key.IdFuncionario
                                  select newGroup;

            model.GradeClientesUnico = ClienteDistinct;
            model.FuncionariosTodos = _funcionarios.GetAll();
            model.ClientesTodos = _clientes.GetAll();
            model.gradeSelected = _grade.Get(id);
            return View(model);
        }


        [HttpPost]
        public IActionResult Edit(GradeIndexViewModel grade)
        {
            var model = new Grade();
            model.Id = grade.gradeSelected.Id;
            model.Ativo = true;
            model.Dia = grade.gradeSelected.Dia;
            model.IdFuncionario = grade.gradeSelected.IdFuncionario;
            model.IdCliente = grade.gradeSelected.IdCliente;
            model.Entrada = grade.gradeSelected.Entrada;
            model.Saida = grade.gradeSelected.Saida;
            model.Inicio = grade.gradeSelected.Inicio;
            model.Fim = grade.gradeSelected.Fim;
            _grade.Update(model);
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public IActionResult Create(GradeIndexViewModel grade)
        {
            var model = new Grade();
            model.Ativo = true;
            model.Dia = grade.gradeSelected.Dia;
            model.IdFuncionario = grade.gradeSelected.IdFuncionario;
            model.IdCliente = grade.gradeSelected.IdCliente;
            model.Entrada = grade.gradeSelected.Entrada;
            model.Saida = grade.gradeSelected.Saida;
            model.Inicio = DateTime.Now.ToString("dd/MM/yyyy");
            _grade.Add(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

Centroserv/Views/Grade/Edit.cshtml
@using Centroserv.Models.ValoresPadroes

@model Centroserv.ViewModels.GradeIndexViewModel;

@{
    ViewData["Title"] = "Edit";
}


<h3 class="text-secondary d-inline">Editar Horario</h3>
<br />
<br />

<form asp-action="Edit" method="post">
    <div class="row">
        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input class="form-control text-primary" asp-for="gradeSelected.Id" type="hidden">
                    <div class="form-row">
                        <div class="form-group col-12">
                            <label class="text-info" asp-for="gradeSelected.IdFuncionario">Funcionario</label>
                            <select asp-for="gradeSelected.IdFuncionario" class="form-control" asp-items="@(new SelectList(Model.FuncionariosTodos, "Id", "Nome"))"></select>
                        </div>
                        <div class="form-group col-12">
                            <label class="text-info" asp-for="gradeSelected.IdCliente">Cliente</label>
                            <select asp-for="gradeSelected.IdCliente" class="form-control" asp-items="@(new SelectList(Model.ClientesTodos, "Id", "Alias"))"></select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="text-info" asp-for="gradeSelected.Dia">Dia</label>
                            <select asp-for="gradeSelected.Dia" class="form-control" asp-items="@Html.GetEnumSelectList<DiasGrade>()"></select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label class="text-info" asp-for="gradeSelected.Entrada">Hora Entrada</label>
                            <input class="form-control text-primary txtHorario" asp-for="gradeSelected.Entrada">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="text-info" asp-for="gradeSelected.Saida">Hora Saida</label>
                            <input class="form-control text-danger txtHorario" asp-for="gradeSelected.Saida">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-2 bg-light border border-info">
            <div class="row">
                <div class="col-md-12" style="padding-top:30px">
                    <h5 class="text-center text-info">Historico</h5>
                    <div class="form-group">
                        <label class="text-info" asp-for="gradeSelected.Inicio">Inicio</label>
                        <input class="form-control txtData" type="text" asp-for="gradeSelected.Inicio" />
                        <label class="text-info" asp-for="gradeSelected.Fim">Valido Ate</label>
                        <input class="form-control txtData" asp-for="gradeSelected.Fim" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div class="col-md-9">
        <hr />
    </div>
    <div class="row col-md-9">
        <div class="col-md-4">
            <input type="submit" value="Salvar Horario" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-link" />Exibir Grade</a>
        </div>
        <div class="col text-right">
            @*<a asp-action="Del" asp-route-id="@Model.gradeSelected.Id" class="btn btn-danger" />Excluir</a>*@
            <a href="#" data-target="#ConfirmaModal" data-toggle="modal" class="btn btn-danger" />Excluir</a>
        </div>
    </div>
</form>



<div class="modal fade" id="ConfirmaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Model.gradeSelected.Clientes.Razao</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="text-primary">
                    <span class="text-dark">Confirma a exclusao?</span><br />
                    @(Model.gradeSelected.Dia + ", das " + @Model.gradeSelected.Entrada + " as " + Model.gradeSelected.Saida)

                </h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Nao</button>
                <a asp-action="Del" asp-route-id="@Model.gradeSelected.Id" class="btn btn-danger">Sim</a>
            </div>
        </div>
    </div>
</div>

Centroserv/Views/Grade/Index.cshtml
@using Centroserv.ViewModels
@using Centroserv.Models.ValoresPadroes
@using Centroserv.Models;

@model GradeIndexViewModel

@{
    ViewData["Title"] = "Grade de Horarios";
}

<h2 class="text-info text-center">Grade de Horarios</h2>

<br />

<table id="TableGrade" class="table table-hover table-sm table-bordered">
    <thead>
        <tr>
            <th class="text-center">Cliente</th>
            <th class="text-center">Funcionario</th>
            <th class="text-center">Segunda</th>
            <th class="text-center">Terca</th>
            <th class="text-center">Quarta</th>
            <th class="text-center">Quinta</th>
            <th class="text-center">Sexta</th>
            <th class="text-center">Sabado</th>
            <th class="text-center">Domingo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var y in Model.GradeClientesUnico)
        {
            <tr>
                @{
                    foreach (var x in y)
                    {
                        <td><a class="text-secondary" asp-action="edit" asp-controller="Clientes" asp-route-id="@x.Clientes.Id">@x.Clientes.Alias</a></td>
                        <td><a class="text-secondary" asp-action="edit" asp-controller="Funcionarios" asp-route-id="@x.Funcionarios.Id">@x.Funcionarios.Alias</a></td>
                        break;
                    }

                    List<Grade> gradeLista = new List<Grade>();
                    foreach (var x in y)
                    {
                        gradeLista.Add(x);
                    }

                    for (int i = 1; i < 8; i++)
                    {
                        <td class="text-center">
                            @{
                                DiasGrade posicao = DiasGrade.Segunda;
                                switch (i)
                                {
                                    case 1:
                                        posicao = DiasGrade.Segunda;
                                        break;
                                    case 2:
                                        posicao = DiasGrade.Terca;
                                        break;
                                    case 3:
                                        posicao = DiasGrade.Quarta;
                                        break;
                                    case 4:
                                        posicao = DiasGrade.Quinta;
                                        break;
                                    case 5:
                                        posicao = DiasGrade.Sexta;
                                        break;
                                    case 6:
                                        posicao = DiasGrade.Sabado;
                                        break;
                                    case 7:
                                        posicao = DiasGrade.Domingo;
                                        break;

                                }
                                var horario = gradeLista.Where(e => e.Dia == posicao);
                                foreach (var x in horario)
                                {
                                    <a asp-action="Edit" asp-route-id="@x.Id" style="@(x.Clientes.Tipo == TipoEstabelecimento.Comercial ? "background-color:lightyellow" : "background-color:")">
                                        <span class="@(string.IsNullOrEmpty(x.Fim) == true ? "text-primary" : "text-secondary")">@x.Entrada</span>
                                        <span>-</span>
                                        <span class="@(string.IsNullOrEmpty(x.Fim) == true ? "text-danger" : "text-secondary")">@x.Saida</span>
                                    </a><br />;
                                }

                            }
                        </td>
                    }
                }
            </tr>
        }


    </tbody>
</table>
<br />
<button id="btnAtivaModal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalNovoHorario">Adicionar Horario</button>



<!-- Modal -->
<div class="modal fade" id="ModalNovoHorario" tabindex="-1" role="dialog" aria-labelledby="ModalNovoHorarioTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form asp-action="Create" method="post">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Adicionar Horario</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label class="text-info" asp-for="gradeSelected.IdFuncionario">Funcionario</label>
                            <select asp-for="gradeSelected.IdFuncionario" class="form-control" asp-items="@(new SelectList(Model.FuncionariosTodos, "Id", "Nome"))"></select>
                        </div>
                        <div class="form-group col-md-5">
                            <label class="text-info" asp-for="gradeSelected.IdCliente">Cliente</label>
                            <select asp-for="gradeSelected.IdCliente" class="form-control" asp-items="@(new SelectList(Model.ClientesTodos, "Id", "Alias"))"></select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label class="text-info" asp-for="gradeSelected.Dia">Dia</label>
                            <select asp-for="gradeSelected.Dia" class="form-control" asp-items="@Html.GetEnumSelectList<DiasGrade>()"></select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label class="text-info" asp-for="gradeSelected.Entrada">Hora Entrada</label>
                            <input class="form-control text-primary txtHorario" asp-for="gradeSelected.Entrada">
                        </div>
                        <div class="form-group col-md-3">
                            <label class="text-info" asp-for="gradeSelected.Saida">Hora Saida</label>
                            <input class="form-control text-danger txtHorario" asp-for="gradeSelected.Saida">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <input type="submit" class="btn btn-primary" value="Salvar Horario">
                </div>
            </form>

        </div>
    </div>
</div>






<script>
        $(document).ready(function () {
            $('#TableGrade').DataTable({
                "dom": 'frtip',
                columnDefs: [{
                    targets: [0, 1, 2, 3],
                    className: 'mdl-data-table__cell--non-numeric'
                }],
                "language": {
                    "search": "Buscar:"
                }

            });
        });
    </script>