Centroserv/Models/Funcionarios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Centroserv.Models.ValoresPadroes;
namespace Centroserv.Models
{
    public class Funcionarios
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Alias { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Fone { get; set; }
        public string Celular { get; set; }
        public string IndicadaPor { get; set; }
        public string Admissao { get; set; }
        public string Saida { get; set; }
        public string Nascimento { get; set; }
        public string Obs { get; set; }
        public string ContatoEmergencia { get; set; }
        public string ContatoEmergenciaCelular { get; set; }
        public string Foto { get; set; }
        public StatusFuncionario Status { get; set; }
        public CargoFuncionario Cargo { get; set; }

        public int Segunda { get; set; }
        public int Terca { get; set; }
        public int Quarta { get; set; }
        public int Quinta { get; set; }
        public int Sexta { get; set; }
        public int Sabado { get; set; }
        public int Domingo { get; set; }
    }
}

Centroserv/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Centroserv.Services;
using Centroserv.ViewModels;
using Centroserv.Models;

namespace Centroserv.Controllers
{
    public class FuncionariosController : Controller
    {
        private IFuncionarios _funcionarios;
        private IFaltas _faltas;
        private IClientes _clientes;
        private IHoraExtra _horasExtra;

        public FuncionariosController(IFuncionarios funcionarios,IFaltas faltas, IClientes clientes,IHoraExtra hora)
        {
            _funcionarios = funcionarios;
            _faltas = faltas;
            _clientes = clientes;
            _horasExtra = hora;
        }


        public IActionResult Index()
        {
            var model = new FuncionariosIndexViewModel();
            model.Funcionarios = _funcionarios.GetAll();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FuncionariosEditViewModel func)
        {
            var model = new Funcionarios()
            {
                Admissao = func.Admissao,
                Alias = func.Alias,
                Bairro = func.Bairro,
                Cargo = func.Cargo,
                Celular = func.Celular,
                Cidade = func.Cidade,
                ContatoEmergencia = func.ContatoEmergencia,
                ContatoEmergenciaCelular = func.ContatoEmergenciaCelular,
                Endereco = func.Endereco,
                Fone = func.Fone,
                IndicadaPor = func.IndicadaPor,
                Nascimento = func.Nascimento,
                Nome = func.Nome,
                Obs = func.Obs,
                Saida = func.Saida,
                Status = func.Status,
                UF = func.UF,
                Segunda = func.Segunda,
                Terca = func.Terca,
                Quarta = func.Quarta,
                Quinta = func.Quinta,
                Sexta = func.Sexta,
                Sabado = func.Sabado,
                Domingo = func.Domingo
                
            };
            _funcionarios.Add(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var func = _funcionarios.Get(id);
            var model = new FuncionariosEditViewModel
            {
                Admissao = func.Admissao,
                Alias = func.Alias,
                Bairro = func.Bairro,
                Cargo = func.Cargo,
                Celular = func.Celular,
                Cidade = func.Cidade,
                ContatoEmergencia = func.ContatoEmergencia,
                ContatoEmergenciaCelular = func.ContatoEmergenciaCelular,
                Endereco = func.Endereco,
                Fone = func.Fone,
                IndicadaPor = func.IndicadaPor,
                Nascimento = func.Nascimento,
                Nome = func.Nome,
                Obs = func.Obs,
                Saida = func.Saida,
                Status = func.Status,
                UF = func.UF,
                Segunda = func.Segunda,
                Terca = func.Terca,
                Quarta = func.Quarta,
                Quinta = func.Quinta,
                Sexta = func.Sexta,
                Sabado = func.Sabado,
                Domingo = func.Domingo,
                Id = func.Id,
                Faltas = _faltas.GetAllByFuncionario(func.Id),
                ClientesTodos = _clientes.GetAll(),
                HorasExtras = _horasExtra.GetAllByFuncionario(id),
                Foto = func.Foto
            };

            return View(model);
        }


        [HttpPost]
        public IActionResult Edit(FuncionariosEditViewModel funcionario)
        {
            var model = new Funcionarios()
            {
                Admissao = funcionario.Admissao,
                Alias = funcionario.Alias,
                Bairro = funcionario.Bairro,
                Cargo = funcionario.Cargo,
                Celular = funcionario.Celular,
                Cidade = funcionario.Cidade,
                ContatoEmergencia = funcionario.ContatoEmergencia,
                ContatoEmergenciaCelular = funcionario.ContatoEmergenciaCelular,
                Domingo = funcionario.Domingo,
                Endereco = funcionario.Endereco,
                Fone = funcionario.Fone,
                IndicadaPor = funcionario.IndicadaPor,
                Nascimento = funcionario.Nascimento,
                Nome = funcionario.Nome,
                Obs = funcionario.Obs,
                Quarta = funcionario.Quarta,
                Quinta = funcionario.Quinta,
                Sexta = funcionario.Sexta,
                Sabado = funcionario.Sabado,
                Saida = funcionario.Saida,
                Segunda = funcionario.Segunda,
                Status = funcionario.Status,
                Terca = funcionario.Terca,
                UF = funcionario.UF,
                Id = funcionario.Id
            };
            _funcionarios.Update(model);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            _funcionarios.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Centroserv/Views/Funcionarios/Create.cshtml
@using Centroserv.ViewModels
@using Centroserv.Models.ValoresPadroes


@model FuncionariosEditViewModel

<h2>Novo Funcionario</h2>

<br />
<form method="post">
    <div class="row text-info">
        <div class="col-lg-6">
            <div class="row ">
                <div class="col-sm-7">
                    <div class="form-group">
                        <label asp-for="Nome"></label>
                        <input type="text" asp-for="Nome" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-group">
                        <label asp-for="Alias"></label>
                        <input type="text" asp-for="Alias" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Cargo"></label>
                        <select asp-for="Cargo" class="form-control" asp-items="@Html.GetEnumSelectList<CargoFuncionario>()"></select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Status"></label>
                        <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<StatusFuncionario>()"></select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Endereco"></label>
                <input type="text" asp-for="Endereco" class="form-control" />
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-group">
                        <label asp-for="Bairro"></label>
                        <input type="text" asp-for="Bairro" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-group">
                        <label asp-for="Cidade"></label>
                        <input type="text" asp-for="Cidade" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label asp-for="UF"></label>
                        <input type="text" asp-for="UF" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Fone"></label>
                        <input type="text" asp-for="Fone" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Celular"></label>
                        <input type="text" asp-for="Celular" class="form-control" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="IndicadaPor"></label>
                        <input type="text" asp-for="IndicadaPor" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="Admissao" ></label>
                        <input type="text" asp-for="Admissao" class="txtData text-success form-control" />
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="Saida"></label>
                        <input type="text" asp-for="Saida" class="txtData text-danger form-control" />
                    </div>
                </div>
            </div>



            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label asp-for="Obs"></label>
                        <textarea asp-for="Obs" class="form-control" rows="5"></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="ContatoEmergencia"></label>
                        <input type="text" asp-for="ContatoEmergencia" class="form-control" />
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="ContatoEmergenciaCelular"></label>
                        <input type="text" asp-for="ContatoEmergenciaCelular" class="form-control" />
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6 ">
            <div class="row ">
                <div class="col-lg-9 bg-light border border-info" style="padding-top:10px">
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Segunda"></label>
                                        <input asp-for="Segunda" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Terca"></label>
                                        <input asp-for="Terca" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Quarta"></label>
                                        <input asp-for="Quarta" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Quinta"></label>
                                        <input asp-for="Quinta" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Sexta"></label>
                                        <input asp-for="Sexta" class="form-control" />
                                    </div>
                                </div>
                                
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Sabado"></label>
                                        <input asp-for="Sabado" class="form-control" />
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label asp-for="Domingo"></label>
                                        <input asp-for="Domingo" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>
                            <p>teste</p>

                        </div>
                        <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="list-group" id="list-tab" role="tablist">
                        <a class="list-group-item list-group-item-action active" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Vale Transporte</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Faltas</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Horas Extras</a>
                    </div>
                </div>
            </div>



        </div>
    </div>
    <hr />
    <br />
    <div class="row">
        <div class="col-6">
            <input type="submit" name="name" value="Gravar" class="btn btn-success" style="width:25%" />
        </div>
        <div class="col-6 text-right">
            <a asp-action="index" class="btn btn-link">Lista de Funcionarios</a>
        </div>

    </div>

</form>
<br />
<br />

Centroserv/Views/Funcionarios/Index.cshtml
@using Centroserv.ViewModels;
@using Centroserv.Models.ValoresPadroes;
@model FuncionariosIndexViewModel;


@{
    //Layout = "~/Views/Shared/_Layout_main.cshtml";

    ViewBag.Title = "Funcionarios Page";
}

<div class="row">
    <div class="col-12 text-info text-center"><h2>Funcionarios</h2></div>
</div>
<a asp-action="Create" class="btn btn-info">Adicionar Funcionario</a>

<br />

<table id="tableFuncionarios" class="table table-sm table-hover ">
    <thead>
        <tr>
            <th></th>
            <th>Status</th>
            <th>Nome</th>
            <th>Cargo</th>
            <th>Celular</th>
            <th>Fone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Funcionarios)
        {
            <tr>
                <td>
                    <img src="@x.Foto" width="60px" class="rounded-circle"  />
                </td>
                <td class="@(x.Status == StatusFuncionario.Contratado ? "text-success" : "text-danger ")">@x.Status</td>
                <td>
                    @x.Nome
                </td>
                <td>@x.Cargo</td>
                <td>@x.Celular</td>
                <td>@x.Fone</td>
                <td>
                    <a asp-action="Edit" asp-controller="Funcionarios" asp-route-id="@x.Id" class="btn btn-outline-info">Editar</a>
                    <a asp-action="Delete" asp-controller="Funcionarios" asp-route-id="@x.Id" class="btn  btn-outline-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>


</table>
<br />


<script>
    $(document).ready(function () {
        $('#tableFuncionarios').DataTable({
            "dom": 'frtip',
            columnDefs: [{
                targets: [0, 1, 2, 3],
                className: 'mdl-data-table__cell--non-numeric'
            }]

        });
    });
</script>