Centroserv/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Centroserv.Services;
using Centroserv.ViewModels;
using Centroserv.Models;

namespace Centroserv.Controllers
{
    public class GradeController : Controller
    {
        private IGrade _grade;
        private IFuncionarios _funcionarios;
        private IClientes _clientes;

        public GradeController(IGrade grade, IFuncionarios funcionarios, IClientes clientes)
        {
            _grade = grade;
            _funcionarios = funcionarios;
            _clientes = clientes;
        }

        
        //[Route("")]
        [Route("grade/index/{MostraTodos?}")]
        public IActionResult Index(string MostraTodos) //id aqui eh usado como flag (mostra todos os horarios ou so ativos)
        {
            var model = new GradeIndexViewModel();
            if (string.IsNullOrEmpty(MostraTodos))
            {
                model.GradeDeHorario = _grade.GettAll(null, null, true);
            }
            else
            {
                model.GradeDeHorario = _grade.GettAll(null, null, false);
            }
            //var ClienteDistinct = model.GradeDeHorario.Select(e => new { e.IdFuncionario, e.IdCliente }).Distinct();
            var ClienteDistinct = from x in model.GradeDeHorario
                                  group x by new { x.IdCliente, x.IdFuncionario } into newGroup
                                  orderby newGroup.Key.IdFuncionario
                                  select newGroup;
                                  
         
            model.GradeClientesUnico = ClienteDistinct;
            model.FuncionariosTodos = _funcionarios.GetAll();
            model.ClientesTodos = _clientes.GetAll();
            return View(model);
        }


        [HttpGet]
        public IActionResult Del(int id)
        {
            var model = _grade.Delete(id);
            return RedirectToAction(nameof(Index));
        }




        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = new GradeIndexViewModel();
            model.GradeDeHorario = _grade.GettAll(null, null, null);
            //var ClienteDistinct = model.GradeDeHorario.Select(e => new { e.IdFuncionario, e.IdCliente }).Distinct();
            var ClienteDistinct = from x in model.GradeDeHorario
                                  group x by new { x.IdCliente, x.IdFuncionario } into newGroup
                                  orderby newGroup.Key.IdFuncionario
                                  select newGroup;

            model.GradeClientesUnico = ClienteDistinct;
            model.FuncionariosTodos = _funcionarios.GetAll();
            model.ClientesTodos = _clientes.GetAll();
            model.gradeSelected = _grade.Get(id);
            return View(model);
        }


        [HttpPost]
        public IActionResult Edit(GradeIndexViewModel grade)
        {
            var model = new Grade();
            model.Id = grade.gradeSelected.Id;
            model.Ativo = true;
            model.Dia = grade.gradeSelected.Dia;
            model.IdFuncionario = grade.gradeSelected.IdFuncionario;
            model.IdCliente = grade.gradeSelected.IdCliente;
            model.Entrada = grade.gradeSelected.Entrada;
            model.Saida = grade.gradeSelected.Saida;
            model.Inicio = grade.gradeSelected.Inicio;
            model.Fim = grade.gradeSelected.Fim;
            _grade.Update(model);
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public IActionResult Create(GradeIndexViewModel grade)
        {
            var model = new Grade();
            model.Ativo = true;
            model.Dia = grade.gradeSelected.Dia;
            model.IdFuncionario = grade.gradeSelected.IdFuncionario;
            model.IdCliente = grade.gradeSelected.IdCliente;
            model.Entrada = grade.gradeSelected.Entrada;
            model.Saida = grade.gradeSelected.Saida;
            model.Inicio = DateTime.Now.ToString("dd/MM/yyyy");
            _grade.Add(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

Centroserv/Views/Shared/_ConfirmaExclusao.cshtml
@*
    Modal generico para exlusao de registros
    <a class="btn btn-link text-danger" data-toggle="modal" data-target="#modalExclui" data-idRegistro="@item.IdEntrega" data-descricaoRegistro="@item.Cliente.Alias" data-nomeController="Entregas">
             Excluir
    </a>

*@


<!-- Modal -->
<div class="modal fade" id="modalExclui" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirma Exclusao</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Confirma exclusao de <span class="text-danger" id="parametro_exclusao"></span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form method="post" name="formDelete">
                    <input type="text" class="btn btn-danger" value="" name="txtIdToDelete" hidden>
                    <input type="submit" class="btn btn-danger" value="Sim! Pode Exlcuir">
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalExclui').on('show.bs.modal', function (e) {

        //get data-id attribute of the clicked element
        var tempMessage = $(e.relatedTarget).data('descricaoregistro');
        var tempId = $(e.relatedTarget).data('idregistro');
        var tempControler = $(e.relatedTarget).data('nomecontroller');


        var tempAction = "/" + tempControler + "/Delete/";
        //populate the textbox
        $("#parametro_exclusao").text(tempMessage);
        $(e.currentTarget).find('input[name="txtIdToDelete"]').val(tempId);
        $(e.currentTarget).find('form[name="formDelete"]').attr('action', tempAction);
    });
</script>

Centroserv/Views/Shared/_EntregaIncluir.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<form asp-action="create" asp-controller="entregas" method="post">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="TituloModalCentralizado">Agendar Entrega de Material</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="dataEntrega">Usuário</label>
                            <input class="form-control" name="txtResponsavel" id="txtResponsavel" style="opacity:0.6"
                                   value="@(User.Identity.IsAuthenticated ? User.Claims.FirstOrDefault(e => e.Type == "name").Value : "")"
                                   disabled />
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="dataEntrega">Previsão Entrega</label>
                            <input class="form-control" name="dataEntrega" value="" type="date" id="idDataEntrega" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="txtCliente">Cliente</label>
                    <div class="autocomplete">
                        <input class="form-control" name="txtCliente" value="" id="txtCliente" />
                        <input class="" name="txtClienteID" id="txtClienteID" hidden />
                    </div>
                </div>



                <div class="form-group">
                    <label for="txtObservacao">Observacao</label>
                    <textarea class="form-control" name="txtObservacao" value="" type="date" id="idObesrvacao"></textarea>
                </div>
                <hr />
                <div class="row" style="background-color:#f3f3f3; padding-top:2%;">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="idDataEntrega">Material</label>
                            <div class="autocomplete">
                                <input class="form-control form-control-sm" name="txtMaterial" id="txtMaterial" placeholder="Digite o material...." />
                                <input class="form-control form-control-sm" name="txtMaterialID" id="txtMaterialID" placeholder="txtMaterialID" disabled hidden />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="idDataEntrega">Quantidade</label>
                            <input class="form-control form-control-sm" name="txtQuantidade" value="" placeholder="Digite qtd..." id="txtQuantidade" />
                            <input class="form-control form-control-sm" name="txtValorUnitario" value="" placeholder="" id="txtValorUnitario" hidden />
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="idUnidade">Unidade</label>
                            <input class="form-control form-control-sm" name="txtUnidade" value="" id="txtUnidade" disabled />
                        </div>
                    </div>
                    <div class="col-lg-1 align-self-center">
                        <div class="form-group">
                            <label for="btnAdd"></label>
                            <button class="btn btn-info btn-sm" onclick="AdicionaItem()" type="button" name="btnAdd" id="btnAdd">Adicionar</button>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="container">
                        <ul id="entregas_lista"></ul>
                    </div>
                </div>
                <div class="row">
                    <div id="entregas_div" class="container">

                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Salvar Entrega</button>
            </div>
        </div>
    </div>
</form>


<style>
    * {
        box-sizing: border-box;
    }

    .autocomplete {
        /*the container must be positioned relative:*/
        position: relative;
        /*display: inline-block;*/
    }


    .autocomplete-items {
        position: absolute;
        border: 1px solid #d4d4d4;
        border-bottom: none;
        border-top: none;
        z-index: 99;
        /*position the autocomplete items to be the same width as the container:*/
        top: 100%;
        left: 0;
        right: 0;
    }

        .autocomplete-items div {
            padding: 10px;
            cursor: pointer;
            background-color: #fff;
            border-bottom: 1px solid #d4d4d4;
        }

            .autocomplete-items div:hover {
                /*when hovering an item:*/
                background-color: #e9e9e9;
            }

    .autocomplete-active {
        /*when navigating through the items using the arrow keys:*/
        background-color: DodgerBlue !important;
        color: #ffffff;
    }
</style>


<script>
    var MateriaisVetor = @{
        <text>[</text>
        foreach (var i in Model.MaterialAll){
            <text>['@i.Descricao', '@i.Unidade', '@i.QtdPadrao', '@i.Id', '@i.ValorUnitario'],</text>
        }
        <text>]</text>
    }

    var ClientesVetor = @{
        <text>[</text>
        foreach(var m in Model.Clientes){
            <text>['@m.Alias','@m.Id'],</text>
        }
        <text>]</text>
    }

</script>
<script src="~/EntregasCreate.js"></script>

Centroserv/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    @*<link rel="icon" type="image/x-icon" href="#" />*@
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="style.css" />
    <script src="script.js"></script>




</head>
<body>


    <!-- SITE WRAPPER -->
    <section id="site-wrapper">
        <!-- CANVAS -->
        <section id="site-canvas">
            <!-- MENU -->
            <section id="site-menu">
                <section class="site-menu-content">
                    <a href="#" class="toggle-nav"><i class="fa fa-times"></i></a>
                    <a href="sass.html"><h2>Dashboard</h2></a>
                    <a asp-action="Index" asp-controller="Clientes"><h2>Clientes</h2></a>
                    <a asp-action="Index" asp-controller="Funcionarios"><h2>Funcionarios</h2></a>
                    <a asp-action="Index" asp-controller="Grade"><h2>Horarios</h2></a>
                </section>
            </section>

            <!-- CANVAS CONTENT -->
            <section class="content">
                <!-- MENU TOGGLE -->
                <div class="row">
                    <div class="col-1">
                        <a href="#" class="toggle-nav nav-icon"><i class="fa fa-bars"></i></a>
                    </div>
                    <div class="col-10 text-right" >
                        Ola Marcus Flores <button type="button" class="btn btn-info">Logout</button>
                    </div>
                </div>
                
                <!-- CONTENT -->
                <div class="col s11 ">
                    @RenderBody()
                </div>

            </section> <!-- END CANVAS CONTENT -->
        </section> <!-- END SITE CONTENT -->
    </section> <!-- END WRAPPER -->




    @*<div class="col s12 right-align" style="background-color:#2d5775">
            <span class="white-text" style="padding-right:10px">Ola, Marcus Flores </span>
            <a class="btn orange" href="collapsible.html" style="margin-top:5px;margin-bottom:5px;margin-right:20px">Logout</a>
        </div>
        <div class="row">
            <div class="col s2 grey darken-3" style="height:100vh">
                <ul>
                    <li><a class="white-text btn waves-light waves-effect green" href="sass.html">Dashboard</a></li>
                    <li><a class="white-text btn btn-flat" asp-action="Index" asp-controller="Clientes">Clientes</a></li>
                    <li><a class="white-text btn btn-flat" asp-action="Index" asp-controller="Funcionarios">Funcionarios</a></li>
                    <li><a class="white-text btn btn-flat" href="collapsible.html">Horarios</a></li>
                </ul>
                <br />
                <br />
                <br />
                <h6 class="yellow-text">Configuracao</h6>
                <ul>
                    <li><a class="white-text btn btn-flat" href="collapsible.html">Material</a></li>
                    <li><a class="white-text btn btn-flat" href="collapsible.html">Imobiliarias</a></li>
                    <li><a class="white-text btn btn-flat" href="collapsible.html">Usuarios</a></li>
                </ul>
       </div>*@


</body>
</html>

Centroserv/Views/Shared/_Layout_main.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    @*<link href='https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>*@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    @*<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>*@
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @*<script language="JavaScript" src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>*@
    @*<script language="JavaScript" src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>*@
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>*@
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://digitalbush.com/wp-content/uploads/2013/01/jquery.maskedinput-1.3.1.min_.js"></script>


    @*<link rel="stylesheet" href="style.css" />
        <script src="script.js"></script>*@
    <script type="text/javascript" src="/libs/bootstrap-filestyle.min.js"></script>
    <link href="/libs/vanillaCalendar.css" rel="stylesheet">

</head>
<body style="width:99%">
    <div class="row">
        <div class="col-12 text-right" style="margin-top:20px">
            @{if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-controller="Security" asp-action="Logout">
                        Ola @User.Claims.FirstOrDefault(e => e.Type == "name").Value
                        <button type="submit" class="btn btn-info">Logout</button>
                    </form>
                    @*@foreach (var x in User.Claims.Where(e => e.Type.ToString() == "groups"))
                    {
                        @x.Value<h5>@x.Type</h5><br />
                    }*@
              

                }
                else
                {
                    <form method="post" asp-controller="Security" asp-action="Login">
                        <button type="submit" class="btn btn-link">Login</button>
                    </form>
                    }
                }
        </div>

    </div>

   
        <br />
        <div class="row">
            <div class="col-12">
                <ul class="nav nav-tabs justify-content-end" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Clientes" class="nav-link ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Imobiliarias" class="nav-link text-secondary">Imobiliarias</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Relatorios</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Material de Limpeza</a>
                            <a class="dropdown-item" href="#">Grade de Horarios</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configuracao</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Material" asp-action="Index">Material de Limpeza</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Usuarios</a>
                        </div>
                    </li>


                    @*<li class="nav-item">
                            <a asp-action="Index" asp-controller="Clientes" class="list-group-item list-group-item-action">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Funcionarios" class="list-group-item list-group-item-action">Funcionarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Horarios</a>
                        </li>
                    *@

                </ul>

            </div>

        </div>
        <br />
        <div class="row">
            <div class="col-2 grey darken-3" style="height:100vh">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active btn-secondary">
                        Menu
                    </a>
                    <a asp-action="Index" asp-controller="agenda" asp-route-id="" class="list-group-item list-group-item-action"><i style="width:30px" class="far fa-calendar-alt "></i> Agenda</a>
                    <a asp-action="Index" asp-controller="despesas" class="list-group-item list-group-item-action"><i style="width:30px" class="fas fa-dollar-sign "></i> Despesas</a>
                    <a asp-action="Index" asp-controller="clientes" class="list-group-item list-group-item-action"><i style="width:30px" class="far fa-building "></i> Clientes</a>
                    <a asp-action="Index" asp-controller="funcionarios" class="list-group-item list-group-item-action"><i style="width:30px" class="fas fa-users "></i> Funcionarios</a>
                    <a asp-action="Index" asp-controller="grade" class="list-group-item list-group-item-action"><i style="width:30px" class="far fa-clock "></i> Horarios</a>
                </div>
            </div>
            <div class="col-10">
                @RenderBody()
            </div>
        </div>





        <script>
            //$(document).ready(function () {
            //    $('.dropdown-toggle').dropdown();
            //});
            $('.txtHorario').mask('99:99');
            $('.txtData').mask('99/99/9999');
        </script>

    </body>
</html>

Centroserv/Views/Shared/_MesAno.cshtml
<style>
    /*.coluna {
        font-size: 15pt;
        background-color: lightyellow;
    }
    .linha {
        height: 40px;
    }*/
</style>

<h1></h1>


<small class="text-info">Selecione o ano e mes das despesas</small>
<div class="row ">
    <div class="col-lg-1 ">
        <input type="number" name="txtAno" id="txtAno" value="@ViewBag.Ano" class="form-control" style="width:100px" />
    </div>
    <div class="col-lg text-left">
        <a class="btn @(ViewBag.Mes == 1 ? "btn-success" : "btn-info")" href="#" onclick="link('01')">Jan</a>
        <a class="btn @(ViewBag.Mes == 2 ? "btn-success" : "btn-info")" href="#" onclick="link('02')">Fev</a>
        <a class="btn @(ViewBag.Mes == 3 ? "btn-success" : "btn-info")" href="#" onclick="link('03')">Mar</a>
        <a class="btn @(ViewBag.Mes == 4 ? "btn-success" : "btn-info")" href="#" onclick="link('04')">Abr</a>
        <a class="btn @(ViewBag.Mes == 5 ? "btn-success" : "btn-info")" href="#" onclick="link('05')">Mai</a>
        <a class="btn @(ViewBag.Mes == 6 ? "btn-success" : "btn-info")" href="#" onclick="link('06')">Jun</a>
        <a class="btn @(ViewBag.Mes == 7 ? "btn-success" : "btn-info")" href="#" onclick="link('07')">Jul</a>
        <a class="btn @(ViewBag.Mes == 8 ? "btn-success" : "btn-info")" href="#" onclick="link('08')">Ago</a>
        <a class="btn @(ViewBag.Mes == 9 ? "btn-success" : "btn-info")" href="#" onclick="link('09')">Set</a>
        <a class="btn @(ViewBag.Mes == 10 ? "btn-success" : "btn-info")" href="#" onclick="link('10')">Out</a>
        <a class="btn @(ViewBag.Mes == 11 ? "btn-success" : "btn-info")" href="#" onclick="link('11')">Nov</a>
        <a class="btn @(ViewBag.Mes == 12 ? "btn-success" : "btn-info")" " href="#" onclick="link('12')">Dez</a>
        <a class="btn btn-link" href="/despesas">Todos</a>
    </div>
</div>





<script>
    function link(e) {
        console.log(e);
        var ano = document.getElementById("txtAno").value;
        var mes = e;
        var url = window.location.href.split("/despesas")
        window.location.href = url[0] + "/despesas/" + ano + "/" + mes;
    }
</script>